### ISSUE TITLE
regolith-desktop changes login screen background before activation?

### ISSUE THREAD

**Issue by arthur-e** [regolith-linux/regolith-desktop#92]
Hello! I'm excited to try `regolith-desktop` and very glad it makes i3 a stand-alone desktop environment alternative. However, after installing it, I noticed that my Ubuntu login screen background was changed to one of the collection of moon/ regolith pictures. I wasn't expecting this (since, at the login screen, I don't feel I've "activated" `regolith-desktop` yet) and I don't like the way it looks. **Maybe this should not be the default behavior after installing `regolith-desktop`?**

To fix it on my machine, I edited `/usr/share/gnome-shell/theme/regolith.css`, setting the `lockDialogGroup` style description's `background` property to match that of `/usr/share/gnome-shell/theme/ubuntu.css`, which is what I was used to seeing before:

```css
#lockDialogGroup {
  background: #2c001e url(resource:///org/gnome/shell/theme/noise-texture.png);
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;
}
```
